5 get/api/reviews
t-cbailey/Tim-Bailey-Public-Repo pull request #5
Opened 2023-05-10 10:59 UTC by t-cbailey

5 get/api/reviews

2023-05-10 11:22 UTC, HannahBurks requested changes
Nice start Tim, a few more changes to make to your tests (we need to make sure they are sorted). Once done please send another pull request

2023-05-10 11:22 UTC, HannahBurks commented on playground.sql
> +\c nc_games_test
Add this to your git ignore :)

2023-05-10 11:22 UTC, HannahBurks commented on __tests__/app.test.js
> +            expect(typeof review.comment_count).toBe("string");
That is fine, SQL turns it to a string, however, you can check by adding + on the test side to check once converted it is infact a number or you can just leave it as is :)

2023-05-10 11:22 UTC, HannahBurks commented on __tests__/app.test.js
> +            expect(typeof review.comment_count).toBe("string");
I would add a test to check the comment count is correct though for one of the article ids.

2023-05-10 11:22 UTC, HannahBurks commented on __tests__/app.test.js
> +  describe("/api/reviews", () => {
You will also need to add a test to ensure they are all sorted - take a look at jest sorted

2023-05-11 08:27 UTC, mezzDavies approved these changes
Changes approved TIm 👍

2023-05-11 09:37 UTC, merged